sequenceDiagram
  Client ->> Function App: CreateQuest
  activate Function App
  Function App ->> Game Engine: CreateQuest
  activate Game Engine
  Game Engine ->> Game Engine: CreateMonster
  Game Engine ->> Monster (Durable Entity): SignalEntity SetHealth
  Game Engine ->> Game Engine: SetPhase
  Game Engine ->> GameState (Durable Entity): SignalEntity SetPhase
  Game Engine ->> Ably: PublishPhase Character
  deactivate Game Engine
  Function App -->> Client: Accepted
  deactivate Function App
