sequenceDiagram
  Client ->> Function App: ExecuteTurn
  activate Function App
  Function App ->> Game Engine: ExecuteTurn
  activate Game Engine
  Game Engine ->> GameState (Durable Entity): Read GameState
  activate GameState (Durable Entity)
  GameState (Durable Entity) -->> Game Engine: GameState
  deactivate GameState (Durable Entity)
  alt IS MONSTER
    Game Engine ->> Game Engine: AttackByMonster
    Game Engine ->> Player (Durable Entity): Signal ApplyDamage
    Game Engine ->> Player (Durable Entity): Read Player
    activate Player (Durable Entity)
    Player (Durable Entity) -->> Game Engine: Player
    deactivate Player (Durable Entity)
  else IS PLAYER
    Game Engine ->> Game Engine: AttackByPlayer
    Game Engine ->> Monster (Durable Entity): Signal ApplyDamage
    Game Engine ->> Monster (Durable Entity): Read Monster
    activate Monster (Durable Entity)
    Monster (Durable Entity) -->> Game Engine: Monster
    deactivate Monster (Durable Entity)
  end
  Game Engine ->> Ably: Publish update-player
  Game Engine ->> Ably: Publish check-player-turn
  Game Engine -->> Function App:
  deactivate Game Engine
  Function App -->> Client: Accepted
  deactivate Function App
