GET http://localhost:7071/api/CreateTokenRequest

### 

GET http://localhost:7071/api/GetQuestExists/ratty-rude

### 

@questId=a-test-again-wow

POST http://localhost:7071/api/CreateQuest
Content-Type: application/text

{{questId}}

###
POST http://localhost:7071/api/AddPlayer
Content-Type: application/json

{
    "questId": "{{questId}}",
    "playerName": "Wiizzz",
    "characterClass": "mage"
}