name: Function App
on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/functionapp.yml'
    - 'api/*'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: serverless-websockets-quest-fa
  LOCATION: westeurope
  RESOURCE_GROUP_NAME: serverless-webockets-quest-rg
  STORAGE_ACCOUNT_NAME: serverlessquest
  FUNCTION_APP_PACKAGE_PATH: '/api'
  DOTNET_VERSION: '6.0.x'
  
jobs:
  FunctionApp:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Azure
      uses: azure/login@v1.4.5
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
    - name: Create Resource Group
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          az group create \
            --name ${{ env.RESOURCE_GROUP_NAME }} \
            --location ${{ env.LOCATION }} \
    - name: Create Storage Account
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          az storage account create \
            --name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --location ${{ env.LOCATION }} \
            --sku Standard_LRS \
            --kind StorageV2 \
            --access-tier Hot
    - name: Create Function App
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          az functionapp create \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --consumption-plan-location ${{ env.LOCATION }} \
            --storage-account ${{ env.STORAGE_ACCOUNT_NAME }} \
            --runtime dotnet \
            --os-type Windows \
            --functions-version 4

    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        pushd './${{ env.FUNCTION_APP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.4.6
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: './${{ env.FUNCTION_APP_PACKAGE_PATH }}/output'
    - name: Set App Settings
      uses: azure/CLI@v1.0.7
      with:
        inlineScript: |
          az functionapp config appsettings set \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --settings \
              "ABLY_APIKEY=${{ secrets.ABLY_APIKEY }}"
